%YAML:1.0

#common parameters
imu_topic: "/imu/imu_uncompensated"
image_topic: "/camera_array/cam2/image_raw"
output_path: "/home/jagatpreet/datasets/"

#camera calibration 
model_type: PINHOLE
camera_name: cam0
image_width: 720
image_height: 540
distortion_parameters:   
   k1: -0.2063053741738656
   k2: 0.15578176050737225
   p1: 0.0012295943267822012
   p2: -0.0006181681426716291
projection_parameters:
   fx: 892.7514933325209
   fy: 891.0437074734942
   cx: 366.8677616144481
   cy: 280.7725980753316

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-0.00795927,0.00147386,0.99996724,
           0.99994463,0.00689582,0.00794893, 
           -0.00688388,0.99997514,-0.00152866]
           
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.038, 0.005, 0.016]

#feature tracker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.078576         # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.028064    # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.00010153         # accelerometer bias random work noise standard deviation.  #3.00e-3
gyr_w: 0.00000396       # gyroscope bias random work noise standard deviation.     #1.93e-5
g_norm: 9.8099

#loop closure parameters
loop_closure: 0                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/jagatpreet/datasets/" # save and load path

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0007                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
