%YAML:1.0
x1:
  - 0
  - 4
  - 11
  - -4
  - 24
  - -3
  - -4
  - -7
  - -5
  - -2
  - 8
  - 1
  - -2
  - -5
  - -5
  - -8
  - 2
  - -8
  - 6
  - 4
  - -1
  - -14
  - 12
  - -12
  - -20
  - -11
  - 7
  - -11
  - 18
  - -10
  - 10
  - -20
  - 7
  - -2
  - 3
  - 7
  - -20
  - -3
  - -4
  - -6
  - -4
  - 14
  - 1
  - 2
  - -9
  - 15
  - 13
  - 14
  - -21
  - -6
  - 3
  - -7
  - 23
  - -22
  - -12
  - 0
  - -22
  - 1
  - -11
  - -11
  - -8
  - -7
  - -16
  - -6
  - 4
  - -16
  - 4
  - 7
  - 0
  - 0
  - -7
  - -4
  - 16
  - -3
  - 6
  - 5
  - 0
  - 8
  - -4
  - -12
  - 0
  - -11
  - 11
  - 3
  - -13
  - 9
  - 11
  - -23
  - 0
  - 6
  - 6
  - 3
  - -7
  - 6
  - 2
  - -4
  - 24
  - -3
  - 5
  - -5
  - 0
  - 0
  - -4
  - -10
  - -1
  - 8
  - 6
  - 3
  - -7
  - 7
  - -4
  - 5
  - 8
  - 10
  - 8
  - -10
  - 2
  - 6
  - 0
  - 10
  - -2
  - 5
  - -2
  - -1
  - -12
  - -10
  - -15
  - 12
  - 1
  - -6
  - 12
  - -7
  - -7
  - -8
  - 7
  - -11
  - 2
  - -22
  - 7
  - 20
  - -8
  - 4
  - 3
  - 11
  - -9
  - 4
  - -4
  - -12
  - 12
  - -22
  - -6
  - 7
  - 5
  - -1
  - 9
  - 10
  - -15
  - -2
  - 1
  - 14
  - 21
  - 3
  - 6
  - -13
  - 5
  - -19
  - 10
  - 6
  - 2
  - -14
  - -16
  - -15
  - 6
  - -8
  - 18
  - 7
  - 16
  - -4
  - -2
  - -4
  - 0
  - -4
  - -14
  - 0
  - -4
  - -13
  - -1
  - -14
  - 11
  - -4
  - -15
  - -8
  - -6
  - 3
  - -1
  - -1
  - 4
  - 8
  - 3
  - 0
  - 24
  - -3
  - -11
  - -10
  - -2
  - 2
  - -1
  - 4
  - 2
  - -1
  - 11
  - 0
  - 10
  - -1
  - 6
  - -4
  - -19
  - 1
  - 9
  - -6
  - -1
  - 12
  - 0
  - -9
  - -1
  - 5
  - 0
  - -6
  - -5
  - 0
  - 7
  - -19
  - 11
  - -9
  - 11
  - 0
  - 8
  - -1
  - 5
  - 10
  - -2
  - -6
  - -6
  - 0
  - -3
  - -7
  - 4
  - -4
  - 2
  - -10
  - -7
  - 18
  - 0
  - 12
  - -2
  - 0
y1:
  - -10
  - 12
  - 13
  - 8
  - -2
  - 2
  - 4
  - 4
  - -11
  - -4
  - 7
  - 15
  - 17
  - 0
  - 10
  - -2
  - -7
  - 10
  - 11
  - -3
  - -4
  - 11
  - -5
  - -15
  - 0
  - 3
  - -3
  - -11
  - 3
  - -4
  - 4
  - 22
  - 16
  - 3
  - -2
  - -3
  - 0
  - 5
  - 15
  - -8
  - 2
  - 2
  - -12
  - -10
  - 5
  - 4
  - 10
  - -4
  - 20
  - -7
  - 5
  - 0
  - -18
  - 2
  - -2
  - -23
  - 15
  - 4
  - -1
  - -2
  - 3
  - 0
  - -16
  - 5
  - 0
  - -16
  - -2
  - 5
  - 6
  - 4
  - 13
  - -1
  - -16
  - -13
  - -7
  - -3
  - 4
  - 0
  - -10
  - -10
  - -9
  - 4
  - -8
  - 0
  - -15
  - -2
  - -10
  - 16
  - 1
  - 0
  - 6
  - -11
  - -3
  - -7
  - -2
  - 10
  - -3
  - -2
  - 0
  - 10
  - -7
  - 0
  - 4
  - 22
  - -5
  - 0
  - -1
  - -8
  - -1
  - -4
  - 12
  - -2
  - 18
  - -2
  - -6
  - -4
  - -2
  - -16
  - -8
  - 1
  - -5
  - 2
  - 3
  - 2
  - 7
  - -8
  - 3
  - 8
  - 0
  - -10
  - -4
  - -18
  - 9
  - 12
  - 3
  - 17
  - -8
  - -13
  - 5
  - -1
  - 8
  - -10
  - -3
  - -9
  - -2
  - 7
  - 5
  - -5
  - -8
  - 15
  - -12
  - -5
  - 0
  - 2
  - 15
  - -5
  - -4
  - -1
  - -9
  - 0
  - -5
  - -11
  - -5
  - -5
  - -10
  - 2
  - 16
  - 6
  - 17
  - 0
  - -7
  - 15
  - 5
  - -14
  - -2
  - 6
  - 5
  - 2
  - 12
  - -3
  - 2
  - 4
  - 13
  - 1
  - -1
  - -3
  - -1
  - -11
  - 8
  - -3
  - 19
  - 8
  - 7
  - -3
  - 5
  - 19
  - 4
  - -6
  - 4
  - -14
  - 3
  - 10
  - -15
  - -4
  - 14
  - 1
  - 14
  - -1
  - -9
  - -5
  - -16
  - 10
  - 6
  - 3
  - -13
  - 19
  - -7
  - -7
  - -12
  - -7
  - 1
  - 7
  - -7
  - 15
  - -2
  - -15
  - 6
  - 6
  - 2
  - -6
  - -16
  - 0
  - -5
  - -9
  - 11
  - 21
  - 3
  - 8
  - 23
  - -5
  - -20
  - -7
  - 13
  - -7
  - -7
  - 0
  - 6
  - 10
  - -15
  - 1
  - 0
  - 0
  - 0
  - -7
  - 10
  - -3
x2:
  - 0
  - 0
  - 13
  - -6
  - 22
  - -7
  - -3
  - -12
  - 1
  - -4
  - 10
  - 4
  - -6
  - 0
  - -8
  - -5
  - 7
  - -2
  - -1
  - 8
  - -2
  - -14
  - 14
  - -10
  - -14
  - -4
  - 6
  - -14
  - 15
  - -5
  - 9
  - -18
  - 4
  - 0
  - -4
  - 3
  - -19
  - -10
  - -8
  - 0
  - -4
  - 10
  - 1
  - 5
  - -12
  - 19
  - 2
  - 11
  - -18
  - -5
  - -3
  - -5
  - 21
  - -17
  - -14
  - 1
  - -17
  - 5
  - -8
  - -8
  - -8
  - -1
  - -16
  - 1
  - -2
  - -12
  - 0
  - 3
  - 7
  - -1
  - -10
  - -2
  - 14
  - -5
  - 0
  - 4
  - -2
  - 15
  - 2
  - -9
  - -9
  - -11
  - 9
  - 2
  - -15
  - 8
  - 9
  - -24
  - -5
  - 10
  - 7
  - 0
  - -7
  - 6
  - 2
  - 0
  - 24
  - 0
  - 2
  - 0
  - 2
  - -1
  - -5
  - -10
  - -4
  - 19
  - 2
  - -6
  - -8
  - 13
  - -1
  - 5
  - 3
  - 13
  - 8
  - -10
  - 0
  - 1
  - -5
  - 11
  - -6
  - 8
  - -7
  - 1
  - -14
  - -6
  - -10
  - 11
  - 2
  - -5
  - 12
  - -12
  - -3
  - -5
  - 7
  - -5
  - -3
  - -16
  - 9
  - 20
  - -9
  - 8
  - 3
  - 15
  - -12
  - 4
  - -6
  - -15
  - 10
  - -17
  - -13
  - 6
  - 4
  - -3
  - 9
  - 7
  - -18
  - -10
  - -3
  - 10
  - 23
  - -9
  - 10
  - -15
  - 7
  - -14
  - 13
  - 10
  - 0
  - -20
  - -14
  - -15
  - 3
  - -7
  - 21
  - 7
  - 17
  - 1
  - 0
  - -2
  - -8
  - -11
  - -17
  - 2
  - -6
  - -18
  - -5
  - -10
  - 5
  - 2
  - -13
  - -6
  - -4
  - 0
  - 3
  - 2
  - 10
  - 10
  - 4
  - 0
  - 21
  - -13
  - -16
  - -17
  - 0
  - 3
  - -1
  - 6
  - 5
  - 8
  - 14
  - 2
  - 10
  - -6
  - 1
  - 0
  - -23
  - 0
  - 6
  - -4
  - 3
  - 9
  - -5
  - -6
  - 1
  - 12
  - 2
  - -6
  - -4
  - 7
  - -1
  - -17
  - 9
  - -12
  - 13
  - -1
  - 11
  - 5
  - 7
  - 10
  - -2
  - -3
  - -8
  - 1
  - 0
  - -6
  - 5
  - -6
  - 5
  - -12
  - -5
  - 21
  - 2
  - 17
  - -7
  - -1
y2:
  - -6
  - 6
  - 10
  - 9
  - 0
  - 4
  - 1
  - 1
  - -12
  - 3
  - 1
  - 9
  - 15
  - 0
  - 14
  - 3
  - -13
  - 11
  - 10
  - -4
  - -2
  - 7
  - -7
  - -17
  - -6
  - 7
  - -4
  - -16
  - -6
  - -2
  - 6
  - 19
  - 8
  - 4
  - -1
  - -2
  - 3
  - 3
  - 21
  - -3
  - 6
  - 5
  - -12
  - -5
  - 0
  - 5
  - 12
  - -5
  - 24
  - -11
  - 7
  - 0
  - -20
  - 0
  - -4
  - -21
  - 15
  - 2
  - -4
  - 0
  - -3
  - 0
  - -19
  - 5
  - 4
  - -19
  - -1
  - 5
  - 4
  - 0
  - 10
  - 3
  - -15
  - -15
  - -7
  - -1
  - 8
  - -6
  - -6
  - -14
  - -15
  - 1
  - -8
  - -1
  - -5
  - 2
  - -10
  - 17
  - 5
  - 0
  - 9
  - -8
  - -5
  - -2
  - -1
  - 9
  - 0
  - -5
  - -2
  - 13
  - -4
  - -1
  - 0
  - 16
  - -10
  - -1
  - 0
  - -6
  - 3
  - -6
  - 10
  - 1
  - 18
  - -2
  - -10
  - -4
  - -1
  - -13
  - -4
  - -1
  - -8
  - 7
  - 4
  - -3
  - 4
  - -14
  - -4
  - 11
  - -1
  - -12
  - -5
  - -14
  - 9
  - 16
  - 1
  - 20
  - -9
  - -10
  - 10
  - 2
  - 4
  - -2
  - -4
  - -6
  - -6
  - 5
  - 5
  - -4
  - 0
  - 18
  - -15
  - -5
  - 0
  - 1
  - 8
  - -4
  - -2
  - 0
  - -11
  - 0
  - -7
  - -5
  - 0
  - 0
  - -3
  - 5
  - 12
  - 3
  - 13
  - 1
  - -9
  - 19
  - 4
  - -9
  - 4
  - 2
  - 3
  - -1
  - 14
  - 0
  - 2
  - 4
  - 14
  - 8
  - 0
  - -4
  - 0
  - -12
  - 9
  - 0
  - 23
  - 7
  - 0
  - -9
  - 2
  - 22
  - 2
  - -14
  - 6
  - -16
  - 1
  - 4
  - -14
  - -10
  - 19
  - 6
  - 16
  - -4
  - -9
  - 0
  - -7
  - 12
  - 5
  - 5
  - -14
  - 21
  - -5
  - -9
  - -17
  - -5
  - 4
  - 14
  - -5
  - 9
  - -4
  - -21
  - 4
  - 1
  - 5
  - 0
  - -12
  - 2
  - 0
  - -1
  - 6
  - 24
  - 0
  - 15
  - 23
  - -10
  - -12
  - -2
  - 12
  - -4
  - -5
  - 0
  - 5
  - 13
  - -21
  - 0
  - -2
  - 1
  - 6
  - -4
  - 9
  - -2
